name: skility_x
description: "app description here"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter  



  # ===================================== DEBUGGIN & PROVACY =====================================
  json_annotation: ^4.9.0                         # json model 
  flutter_dotenv: ^5.2.1                          # handles the environment variables
  
  # ======================================== UI ==========================================
  cached_network_image: ^3.4.1                    # caches the network images
  flutter_launcher_icons: ^0.14.3                 # changes the app logo
  hexcolor: ^3.0.1                                # helps utilizing hex colors in dart
  dot_curved_bottom_nav: ^0.0.2                   # navigation bar
  flutter_screenutil: ^5.9.3                      # handles the figma file size
  flutter_svg: ^2.1.0                             # displays .svg type images
  flutter_spinkit: ^5.2.1                         # loading indicators


  # ======================================== FIREBASE ==========================================
  firebase_core: ^3.13.0                          # firebase setup
  firebase_crashlytics: ^4.3.5                    # crash catch
  cloud_firestore: ^5.6.7                         # firestore


  # ======================================== PERMISSIONS ==========================================
  app_settings: ^6.1.1                            # wifi, notification and other permissions
  path_provider: ^2.1.5                           # handles permissions
  
  # ======================================== STATE MANAGEMENT ==========================================
  riverpod: ^2.6.1                                # handles the state
  flutter_riverpod: ^2.6.1                        # helps to integrate riverpod in flutter projects

dev_dependencies:
  flutter_test:
    sdk: flutter

  # classs model generator
  json_serializable: ^6.7.1 # lowered the version for compatibility with hive generator

  # built scripts ( ast development stage only)
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/all_icons/layers/Layer_1.png"
  min_sdk_android: 23

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  # layers
    - assets/all_icons/layers/


  # app logo path
    - assets/all_icons/layers/Layer_1.png

  # app home icons path
    - assets/all_icons/bottom_nav_bar/
    - assets/all_icons/icons/
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: LobsterFont
      fonts:
        - asset: assets/Fonts/LobsterFont/Lobster-Regular.ttf
    
    - family: SyneRegularFont
      fonts:
        - asset: assets/Fonts/SyneFont/Syne-Regular.ttf
    - family: SyneBoldFont
      fonts:
        - asset: assets/Fonts/SyneFont/Syne-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
